// *********** Configuration *********** //
:lang: en
:toclevels: 4
:toc-placement: right
:icons: font
:sectanchors:
:experimental:
:sectnums:
:source-highlighter: coderay
:toc-title: Table of Contents
:caution-caption: Caution
:important-caption: Important
:note-caption: Note
:tip-caption: Tip
:warning-caption: Warning
:appendix-caption: Appendix
:example-caption: Example
:figure-caption: Figure
:table-caption: Table

// *********** Terms *********** //
:nav: Navigation Service
:navs: Navigation Service endpoint
:navm: Navigation Service module
:servicename: Navigation Client Service
:fsmname: navigation-service
:espirit: e-Spirit AG
:fs: FirstSpirit
:server: FirstSpirit server
:sa: SiteArchitect
:sm: ServerManager
:p_settings: Project settings
:pak: project component
:caas: Content as a Service

// *********** Buttons *********** //
:install: btn:[Install]
:open: btn:[Open]
:config: btn:[Configure]
:add: btn:[Add]
:ok: btn:[OK]

== Authentication
In the current version of the {nav} stack the following aspects have to be considered during project development.

=== Authentication for read access
Please note that per default there are no authentication/authorisation procedures for all GET requests against the navigation endpoints.
This only applies to reading navigations - all writing operations require authentication/authorization.
As a result, every editorial change to a {fs} project with an activated {nav} {pak} is directly transferred to the preview navigation and is therefore accessible to everyone.

If necessary, GET requests can also be blocked either only for preview navigations or completely.
Please contact e-Spirit support for this purpose.